name: Daily Redeploy to gh-pages

# Trigger this workflow every day at midnight UTC
on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch: # Allows manual trigger as well

permissions:
  contents: write

jobs:
  update-data-and-deploy:
    runs-on: ubuntu-latest # You can use other runners as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run script to update JSON data
        run: |
          node scripts/getSteamLastPlayedData.js

      - name: Configure Git identity
        run: |
          git config --global user.email "masaakikaeru@gmail.com"
          git config --global user.name "masaaki"

      - name: Deploy
        run: npm run deploy

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }} 
      #     branch: gh-pages
      #     folder: build
      #     target_commitish: main
