name: Nigthly Redeploy 

on:
  schedule:
    - cron: '0 1 * * *'  # 1:00 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy
        run: npm run deploy
