name: Nigthly Redeploy 

on:
  schedule:
    - cron: '0 1 * * *'  # 1:00 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      # - name: Build project
      #   run: npm run build
      #
      - name: Deploy
        run: npm run deploy

      # - name: Deploy to gh-pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: gh-pages
      #     folder: build
